apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./dev-config.yaml
- ../base
- ./dev-quotas.yaml
- ./dev-database.yaml
patchesStrategicMerge:
- ./dev-patch.yaml
images:
- name: metrics-image
  newName: metrics-amd64
  newTag: "1.0"
- name: openzipkin
  newName: openzipkin/zipkin
  newTag: "2.23"
- name: sales-api-image
  newName: sales-api-amd64
  newTag: "1.0"
