# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  shared-network:
    driver: bridge

services:

  # This starts a local PostgreSQL DB.
  db:
    container_name: sales_db
    networks:
      - shared-network
    image: postgres:11.1-alpine
    ports:
      - 5432:5432

  # This is the core CRUD based service.
  sales-api:
    container_name: sales-api
    networks:
      - shared-network
    image: gcr.io/sales-api/sales-api-amd64:1.0
    ports:
      - 3000:3000 # CRUD API
      - 4000:4000 # DEBUG API
    environment:
      - SALES_AUTH_KEY_ID=1
      # - GODEBUG=gctrace=1

  # This sidecar publishes metrics to the console by default.
  metrics:
    container_name: metrics
    networks:
      - shared-network
    image: gcr.io/sales-api/metrics-amd64:1.0
    ports:
      - 3001:3001 # EXPVAR API
      - 4001:4001 # DEBUG API

  # This sidecar publishes tracing to the console by default.
  tracer:
    container_name: tracer
    networks:
      - shared-network
    image: gcr.io/sales-api/tracer-amd64:1.0
    ports:
      - 3002:3002 # TRACER API
      - 4002:4002 # DEBUG API
    # environment:
      # - SALES_ZIPKIN_HOST=http://zipkin:9411/api/v2/spans

  # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin:2.11
    ports:
      - 9411:9411
