apiVersion: v1
kind: Service
metadata:
  name: sales-api
spec:
  selector:
    service: sales-api
  ports:
  - name: "zipkin"
    port: 9411
    targetPort: 9411
  - name: "sales-api"
    port: 3000
    targetPort: 3000
  - name: "metrics"
    port: 3001
    targetPort: 3001
status:
  loadBalancer: {}