apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-pod # Base POD name
  namespace: sales-system
spec:
  selector:
    matchLabels:
      app: vault # Selector for POD name search.
  template:
    metadata:
      labels:
        app: vault
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      # zipkin container configuration
      - name: vault
        image: hashicorpvault
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: root_token_id
        - name: VAULT_DEV_LISTEN_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: listen_address
---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: sales-system
spec:
  type: ClusterIP
  selector:
    app: vault
