 version: 2
 jobs:
   build:
     machine:
       image: ubuntu-1604:201903-01
     steps:
       - checkout                              # Get the source code.
       # You may want to install your own Go here. The default Go in machine is v1.10.3.
       - run: docker pull postgres:11.1-alpine # Download the DB image used in tests.
       - run:
           name: Run tests on remote docker host
           command: |
               # Get a list of unique non-vendor directories containing test files.
               # $pkg will be like ./internal/platform/conf
               for pkg in $(find . -name "*_test.go" -not -wholename "*vendor*" -exec dirname {} \; | uniq); do
                 test=$(echo "${pkg}.test" | sed 's@.*/@@')                  # convert "./internal/platform/conf" to "conf.test"
                 GO111MODULE=on go test -race -mod=readonly -c $pkg -o $test # Build the test binary
                 scp "$test" remote-docker:"$test"                           # Copy it to the remote docker host
                 echo "Testing $pkg"                                         #
                 ssh remote-docker ./"$test" -test.v                         # Run the tests on the remote host
               done
