# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'
networks:
  shared-network:
    driver: bridge
services:
  crud:
    networks:
      - shared-network
    image: crud-amd64:1
    ports:
        - 3000:3000
        - 4000:4000
  metrics:
    networks:
      - shared-network
    image: metrics-amd64:1
volumes:
    console-data: