apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-pod
  namespace: sales-system
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: sales-api

        # Give Kubernetes enough time to stop sending traffic to the Pod while it is shutting down.
        # https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - "sleep 5"
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system
spec:
  selector:
    app: sales
  type: LoadBalancer
