apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kind-vault-config.yaml
  - ./kind-vault.yaml
patchesStrategicMerge:
  - ./kind-vault-patch.yaml
images:
  - name: hashicorpvault
    newName: hashicorp/vault
    newTag: "1.12"
