apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  replicas: 1
  
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: sales

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
      - name: sales-api
        resources:
          requests:
            cpu: "250m" # 25ms for every 100ms on a single core
            memory: 500Mi
          limits:
            cpu: "250m" # 25ms for every 100ms on a single core
            memory: 500Mi

        volumeMounts:
          - name: vault
            mountPath: /vault

      - name: metrics
        resources:
          requests:
            cpu: "125m" # 12.5ms for every 100ms on a single core
            memory: 250Mi
          limits:
            cpu: "125m" # 12.5ms for every 100ms on a single core
            memory: 250Mi
