apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  replicas: 1
  
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: sales

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
      - name: sales-api
        resources:
          requests:
            cpu: "1000m" # I need access to 1 core on the node.
            memory: 500Mi
          limits:
            cpu: "1000m" # Execute instructions 100ms/100ms on my 1 core.
            memory: 500Mi

        volumeMounts:
          - name: vault
            mountPath: /vault

      - name: metrics
        resources:
          requests:
            cpu: "500m" # I need access to 1/2 core on the node.
            memory: 250Mi
          limits:
            cpu: "500m" # Execute instructions 50ms/100ms on my 1/2 core.
            memory: 250Mi
