apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  replicas: 1
  
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: sales

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
      - name: sales-api
        resources:
          requests:
            cpu: "250m" # quarter as much CPU time
            memory: 500Mi
          limits:
            cpu: "250m" # quarter as much CPU time
            memory: 500Mi

        volumeMounts:
          - name: vault
            mountPath: /vault

      - name: metrics
        resources:
          requests:
            cpu: "125m" # eighth as much CPU time
            memory: 250Mi
          limits:
            cpu: "125m" # eighth as much CPU time
            memory: 250Mi
