apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./kind-sales-config.yaml
- ../../base/sales/
patchesStrategicMerge:
- ./kind-sales-patch.yaml
images:
- name: sales-api-image
  newName: sales-api
  newTag: "1.0"
- name: metrics-image
  newName: metrics
  newTag: "1.0"
